
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS8 set_model_6060[3];		/* Mapped at index 0x2000, subindex 0x01 - 0x03 */
extern UNS32 set_velocity_60ff[3];		/* Mapped at index 0x2001, subindex 0x01 - 0x03 */
extern INTEGER16 set_torque_6071[3];		/* Mapped at index 0x2002, subindex 0x01 - 0x03 */
extern INTEGER16 rec_torqur_6077[3];		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
extern INTEGER16 rec_current_6078[3];		/* Mapped at index 0x2004, subindex 0x01 - 0x03 */
extern INTEGER32 rec_position_6064[3];		/* Mapped at index 0x2005, subindex 0x01 - 0x03 */
extern INTEGER16 rec_temp_2326_1[3];		/* Mapped at index 0x2006, subindex 0x01 - 0x03 */
extern INTEGER16 rec_temp_2326_2[3];		/* Mapped at index 0x2007, subindex 0x01 - 0x03 */
extern INTEGER16 rec_temp_2326_3[3];		/* Mapped at index 0x2008, subindex 0x01 - 0x03 */

#endif // MASTER_H
