
/* File generated by gen_cfile.py. Should not be modified. */

#include "Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 set_model_6060[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 set_velocity_60ff[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 set_torque_6071[] =		/* Mapped at index 0x2002, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 rec_torqur_6077[] =		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 rec_current_6078[] =		/* Mapped at index 0x2004, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER32 rec_position_6064[] =		/* Mapped at index 0x2005, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 rec_temp_2326_1[] =		/* Mapped at index 0x2006, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 rec_temp_2326_2[] =		/* Mapped at index 0x2007, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 rec_temp_2326_3[] =		/* Mapped at index 0x2008, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Master_obj1005 = 0x7E;	/* 126 */
                    subindex Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Master_obj1006 = 0x9C4;	/* 2500 */
                    subindex Master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1006, NULL }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 Master_obj1007 = 0x9C4;	/* 2500 */
                    subindex Master_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1007, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Master_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 Master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 Master_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex Master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Master_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1403_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 Master_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1404_COB_ID_used_by_PDO = 0x282;	/* 642 */
                    UNS8 Master_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1404, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1404_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_SYNC_start_value, NULL }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1405_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 Master_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1405, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1405_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x20040108	/* 537133320 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x20040208	/* 537133576 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x20040308	/* 537133832 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1603 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1603[] = 
                    {
                      0x20060110,	/* 537264400 */
                      0x20070110,	/* 537329936 */
                      0x20080110	/* 537395472 */
                    };
                    subindex Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[2], NULL }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1604 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1604[] = 
                    {
                      0x20060210,	/* 537264656 */
                      0x20070210,	/* 537330192 */
                      0x20080210	/* 537395728 */
                    };
                    subindex Master_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1604, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[2], NULL }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 Master_highestSubIndex_obj1605 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1605[] = 
                    {
                      0x20060310,	/* 537264912 */
                      0x20070310,	/* 537330448 */
                      0x20080310	/* 537395984 */
                    };
                    subindex Master_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1605, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[2], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 Master_obj1800_Transmission_Type = 0x2;	/* 2 */
                    UNS16 Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1801_COB_ID_used_by_PDO = 0x202;	/* 514 */
                    UNS8 Master_obj1801_Transmission_Type = 0x2;	/* 2 */
                    UNS16 Master_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1802_COB_ID_used_by_PDO = 0x203;	/* 515 */
                    UNS8 Master_obj1802_Transmission_Type = 0x2;	/* 2 */
                    UNS16 Master_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x20000108,	/* 536871176 */
                      0x20010108	/* 536936712 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[1], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A01[] = 
                    {
                      0x20000208,	/* 536871432 */
                      0x20010208	/* 536936968 */
                    };
                    subindex Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[1], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1A02[] = 
                    {
                      0x20000308,	/* 536871688 */
                      0x20010308	/* 536937224 */
                    };
                    subindex Master_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[1], NULL }
                     };

/* index 0x2000 :   Mapped variable set_model_6060 */
                    UNS8 Master_highestSubIndex_obj2000 = 3; /* number of subindex - 1*/
                    subindex Master_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2000, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&set_model_6060[0], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&set_model_6060[1], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&set_model_6060[2], NULL }
                     };

/* index 0x2001 :   Mapped variable set_velocity_60ff */
                    UNS8 Master_highestSubIndex_obj2001 = 3; /* number of subindex - 1*/
                    subindex Master_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2001, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&set_velocity_60ff[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&set_velocity_60ff[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&set_velocity_60ff[2], NULL }
                     };

/* index 0x2002 :   Mapped variable set_torque_6071 */
                    UNS8 Master_highestSubIndex_obj2002 = 3; /* number of subindex - 1*/
                    subindex Master_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2002, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&set_torque_6071[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&set_torque_6071[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&set_torque_6071[2], NULL }
                     };

/* index 0x2003 :   Mapped variable rec_torqur_6077 */
                    UNS8 Master_highestSubIndex_obj2003 = 3; /* number of subindex - 1*/
                    subindex Master_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2003, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_torqur_6077[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_torqur_6077[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_torqur_6077[2], NULL }
                     };

/* index 0x2004 :   Mapped variable rec_current_6078 */
                    UNS8 Master_highestSubIndex_obj2004 = 3; /* number of subindex - 1*/
                    subindex Master_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2004, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_current_6078[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_current_6078[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_current_6078[2], NULL }
                     };

/* index 0x2005 :   Mapped variable rec_position_6064 */
                    UNS8 Master_highestSubIndex_obj2005 = 3; /* number of subindex - 1*/
                    subindex Master_Index2005[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2005, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&rec_position_6064[0], NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&rec_position_6064[1], NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&rec_position_6064[2], NULL }
                     };

/* index 0x2006 :   Mapped variable rec_temp_2326_1 */
                    UNS8 Master_highestSubIndex_obj2006 = 3; /* number of subindex - 1*/
                    subindex Master_Index2006[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2006, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_1[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_1[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_1[2], NULL }
                     };

/* index 0x2007 :   Mapped variable rec_temp_2326_2 */
                    UNS8 Master_highestSubIndex_obj2007 = 3; /* number of subindex - 1*/
                    subindex Master_Index2007[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2007, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_2[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_2[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_2[2], NULL }
                     };

/* index 0x2008 :   Mapped variable rec_temp_2326_3 */
                    UNS8 Master_highestSubIndex_obj2008 = 3; /* number of subindex - 1*/
                    subindex Master_Index2008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2008, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_3[0], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_3[1], NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&rec_temp_2326_3[2], NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1005,sizeof(Master_Index1005)/sizeof(Master_Index1005[0]), 0x1005},
  { (subindex*)Master_Index1006,sizeof(Master_Index1006)/sizeof(Master_Index1006[0]), 0x1006},
  { (subindex*)Master_Index1007,sizeof(Master_Index1007)/sizeof(Master_Index1007[0]), 0x1007},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1280,sizeof(Master_Index1280)/sizeof(Master_Index1280[0]), 0x1280},
  { (subindex*)Master_Index1281,sizeof(Master_Index1281)/sizeof(Master_Index1281[0]), 0x1281},
  { (subindex*)Master_Index1282,sizeof(Master_Index1282)/sizeof(Master_Index1282[0]), 0x1282},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1403,sizeof(Master_Index1403)/sizeof(Master_Index1403[0]), 0x1403},
  { (subindex*)Master_Index1404,sizeof(Master_Index1404)/sizeof(Master_Index1404[0]), 0x1404},
  { (subindex*)Master_Index1405,sizeof(Master_Index1405)/sizeof(Master_Index1405[0]), 0x1405},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1603,sizeof(Master_Index1603)/sizeof(Master_Index1603[0]), 0x1603},
  { (subindex*)Master_Index1604,sizeof(Master_Index1604)/sizeof(Master_Index1604[0]), 0x1604},
  { (subindex*)Master_Index1605,sizeof(Master_Index1605)/sizeof(Master_Index1605[0]), 0x1605},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1801,sizeof(Master_Index1801)/sizeof(Master_Index1801[0]), 0x1801},
  { (subindex*)Master_Index1802,sizeof(Master_Index1802)/sizeof(Master_Index1802[0]), 0x1802},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index1A01,sizeof(Master_Index1A01)/sizeof(Master_Index1A01[0]), 0x1A01},
  { (subindex*)Master_Index1A02,sizeof(Master_Index1A02)/sizeof(Master_Index1A02[0]), 0x1A02},
  { (subindex*)Master_Index2000,sizeof(Master_Index2000)/sizeof(Master_Index2000[0]), 0x2000},
  { (subindex*)Master_Index2001,sizeof(Master_Index2001)/sizeof(Master_Index2001[0]), 0x2001},
  { (subindex*)Master_Index2002,sizeof(Master_Index2002)/sizeof(Master_Index2002[0]), 0x2002},
  { (subindex*)Master_Index2003,sizeof(Master_Index2003)/sizeof(Master_Index2003[0]), 0x2003},
  { (subindex*)Master_Index2004,sizeof(Master_Index2004)/sizeof(Master_Index2004[0]), 0x2004},
  { (subindex*)Master_Index2005,sizeof(Master_Index2005)/sizeof(Master_Index2005[0]), 0x2005},
  { (subindex*)Master_Index2006,sizeof(Master_Index2006)/sizeof(Master_Index2006[0]), 0x2006},
  { (subindex*)Master_Index2007,sizeof(Master_Index2007)/sizeof(Master_Index2007[0]), 0x2007},
  { (subindex*)Master_Index2008,sizeof(Master_Index2008)/sizeof(Master_Index2008[0]), 0x2008},
};

const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1007: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1281: i = 7;break;
		case 0x1282: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1403: i = 12;break;
		case 0x1404: i = 13;break;
		case 0x1405: i = 14;break;
		case 0x1600: i = 15;break;
		case 0x1601: i = 16;break;
		case 0x1602: i = 17;break;
		case 0x1603: i = 18;break;
		case 0x1604: i = 19;break;
		case 0x1605: i = 20;break;
		case 0x1800: i = 21;break;
		case 0x1801: i = 22;break;
		case 0x1802: i = 23;break;
		case 0x1A00: i = 24;break;
		case 0x1A01: i = 25;break;
		case 0x1A02: i = 26;break;
		case 0x2000: i = 27;break;
		case 0x2001: i = 28;break;
		case 0x2002: i = 29;break;
		case 0x2003: i = 30;break;
		case 0x2004: i = 31;break;
		case 0x2005: i = 32;break;
		case 0x2006: i = 33;break;
		case 0x2007: i = 34;break;
		case 0x2008: i = 35;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  9, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  21, /* PDO_TRS */
  24 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  0, /* SDO_SVR */
  8, /* SDO_CLT */
  14, /* PDO_RCV */
  20, /* PDO_RCV_MAP */
  23, /* PDO_TRS */
  26 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

