from building import *
import os

cwd     = GetCurrentDir()
src_dir = os.path.join(cwd, 'src')
inc_dir = os.path.join(cwd, 'inc')

CPPPATH = [cwd, inc_dir]
src = Glob('*.c') + Glob(os.path.join(src_dir, '*.c'))

if GetDepend(['PKG_USING_RTDUINO']) and not GetDepend(['RTDUINO_NO_SETUP_LOOP']):
    src += ['arduino_main.cpp']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
