
/* File generated by gen_cfile.py. Should not be modified. */

#include "nimotion.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 target_torque_6071 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 torque_actual_value_6077 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 max_velocity_6080 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 nimotion_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 nimotion_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 nimotion_iam_a_slave = 0;

TIMER_HANDLE nimotion_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 nimotion_obj1000 = 0x0;	/* 0 */
                    subindex nimotion_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 nimotion_obj1001 = 0x0;	/* 0 */
                    subindex nimotion_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 nimotion_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 nimotion_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex nimotion_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 nimotion_obj1005 = 0x80;	/* 128 */
                    subindex nimotion_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 nimotion_obj1006 = 0x2710;	/* 10000 */
                    subindex nimotion_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 nimotion_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 nimotion_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 nimotion_obj1014 = 0x80;	/* 128 */
                    subindex nimotion_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 nimotion_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 nimotion_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex nimotion_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1016[0], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 nimotion_obj1017 = 0x0;	/* 0 */
                    subindex nimotion_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 nimotion_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 nimotion_obj1018_Vendor_ID = 0x123456;	/* 1193046 */
                    UNS32 nimotion_obj1018_Product_Code = 0x1;	/* 1 */
                    UNS32 nimotion_obj1018_Revision_Number = 0x1;	/* 1 */
                    UNS32 nimotion_obj1018_Serial_Number = 0x12345678;	/* 305419896 */
                    subindex nimotion_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 nimotion_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex nimotion_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&nimotion_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 nimotion_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 nimotion_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 nimotion_obj1280_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex nimotion_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 nimotion_obj1400_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 nimotion_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 nimotion_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 nimotion_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 nimotion_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 nimotion_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex nimotion_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 nimotion_obj1401_COB_ID_used_by_PDO = 0x282;	/* 642 */
                    UNS8 nimotion_obj1401_Transmission_Type = 0x1;	/* 1 */
                    UNS16 nimotion_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 nimotion_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 nimotion_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 nimotion_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex nimotion_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 nimotion_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1600[] = 
                    {
                      0x60410010,	/* 1614872592 */
                      0x60640020	/* 1617166368 */
                    };
                    subindex nimotion_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1600[1], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 nimotion_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1601[] = 
                    {
                      0x606C0020,	/* 1617690656 */
                      0x20010008	/* 536936456 */
                    };
                    subindex nimotion_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1601[1], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 nimotion_obj1800_COB_ID_used_by_PDO = 0x202;	/* 514 */
                    UNS8 nimotion_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 nimotion_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 nimotion_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 nimotion_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 nimotion_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex nimotion_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 nimotion_obj1801_COB_ID_used_by_PDO = 0x302;	/* 770 */
                    UNS8 nimotion_obj1801_Transmission_Type = 0x1;	/* 1 */
                    UNS16 nimotion_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 nimotion_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 nimotion_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 nimotion_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex nimotion_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 nimotion_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 nimotion_obj1802_COB_ID_used_by_PDO = 0x402;	/* 1026 */
                    UNS8 nimotion_obj1802_Transmission_Type = 0x1;	/* 1 */
                    UNS16 nimotion_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 nimotion_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 nimotion_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 nimotion_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex nimotion_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&nimotion_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 nimotion_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1A00[] = 
                    {
                      0x60400010,	/* 1614807056 */
                      0x60600008	/* 1616904200 */
                    };
                    subindex nimotion_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A00[1], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 nimotion_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1A01[] = 
                    {
                      0x607A0020,	/* 1618608160 */
                      0x60FF0020	/* 1627324448 */
                    };
                    subindex nimotion_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A01[1], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 nimotion_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 nimotion_obj1A02[] = 
                    {
                      0x20000008,	/* 536870920 */
                      0x20020008	/* 537001992 */
                    };
                    subindex nimotion_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&nimotion_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&nimotion_obj1A02[1], NULL }
                     };

/* index 0x2000 :   Mapped variable target_torque_6071 */
                    subindex nimotion_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&target_torque_6071, NULL }
                     };

/* index 0x2001 :   Mapped variable torque_actual_value_6077 */
                    subindex nimotion_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&torque_actual_value_6077, NULL }
                     };

/* index 0x2002 :   Mapped variable max_velocity_6080 */
                    subindex nimotion_Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&max_velocity_6080, NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex nimotion_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex nimotion_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex nimotion_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation, NULL }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex nimotion_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex nimotion_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex nimotion_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex nimotion_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable nimotion_objdict[] = 
{
  { (subindex*)nimotion_Index1000,sizeof(nimotion_Index1000)/sizeof(nimotion_Index1000[0]), 0x1000},
  { (subindex*)nimotion_Index1001,sizeof(nimotion_Index1001)/sizeof(nimotion_Index1001[0]), 0x1001},
  { (subindex*)nimotion_Index1005,sizeof(nimotion_Index1005)/sizeof(nimotion_Index1005[0]), 0x1005},
  { (subindex*)nimotion_Index1006,sizeof(nimotion_Index1006)/sizeof(nimotion_Index1006[0]), 0x1006},
  { (subindex*)nimotion_Index1014,sizeof(nimotion_Index1014)/sizeof(nimotion_Index1014[0]), 0x1014},
  { (subindex*)nimotion_Index1016,sizeof(nimotion_Index1016)/sizeof(nimotion_Index1016[0]), 0x1016},
  { (subindex*)nimotion_Index1017,sizeof(nimotion_Index1017)/sizeof(nimotion_Index1017[0]), 0x1017},
  { (subindex*)nimotion_Index1018,sizeof(nimotion_Index1018)/sizeof(nimotion_Index1018[0]), 0x1018},
  { (subindex*)nimotion_Index1200,sizeof(nimotion_Index1200)/sizeof(nimotion_Index1200[0]), 0x1200},
  { (subindex*)nimotion_Index1280,sizeof(nimotion_Index1280)/sizeof(nimotion_Index1280[0]), 0x1280},
  { (subindex*)nimotion_Index1400,sizeof(nimotion_Index1400)/sizeof(nimotion_Index1400[0]), 0x1400},
  { (subindex*)nimotion_Index1401,sizeof(nimotion_Index1401)/sizeof(nimotion_Index1401[0]), 0x1401},
  { (subindex*)nimotion_Index1600,sizeof(nimotion_Index1600)/sizeof(nimotion_Index1600[0]), 0x1600},
  { (subindex*)nimotion_Index1601,sizeof(nimotion_Index1601)/sizeof(nimotion_Index1601[0]), 0x1601},
  { (subindex*)nimotion_Index1800,sizeof(nimotion_Index1800)/sizeof(nimotion_Index1800[0]), 0x1800},
  { (subindex*)nimotion_Index1801,sizeof(nimotion_Index1801)/sizeof(nimotion_Index1801[0]), 0x1801},
  { (subindex*)nimotion_Index1802,sizeof(nimotion_Index1802)/sizeof(nimotion_Index1802[0]), 0x1802},
  { (subindex*)nimotion_Index1A00,sizeof(nimotion_Index1A00)/sizeof(nimotion_Index1A00[0]), 0x1A00},
  { (subindex*)nimotion_Index1A01,sizeof(nimotion_Index1A01)/sizeof(nimotion_Index1A01[0]), 0x1A01},
  { (subindex*)nimotion_Index1A02,sizeof(nimotion_Index1A02)/sizeof(nimotion_Index1A02[0]), 0x1A02},
  { (subindex*)nimotion_Index2000,sizeof(nimotion_Index2000)/sizeof(nimotion_Index2000[0]), 0x2000},
  { (subindex*)nimotion_Index2001,sizeof(nimotion_Index2001)/sizeof(nimotion_Index2001[0]), 0x2001},
  { (subindex*)nimotion_Index2002,sizeof(nimotion_Index2002)/sizeof(nimotion_Index2002[0]), 0x2002},
  { (subindex*)nimotion_Index6040,sizeof(nimotion_Index6040)/sizeof(nimotion_Index6040[0]), 0x6040},
  { (subindex*)nimotion_Index6041,sizeof(nimotion_Index6041)/sizeof(nimotion_Index6041[0]), 0x6041},
  { (subindex*)nimotion_Index6060,sizeof(nimotion_Index6060)/sizeof(nimotion_Index6060[0]), 0x6060},
  { (subindex*)nimotion_Index6064,sizeof(nimotion_Index6064)/sizeof(nimotion_Index6064[0]), 0x6064},
  { (subindex*)nimotion_Index606C,sizeof(nimotion_Index606C)/sizeof(nimotion_Index606C[0]), 0x606C},
  { (subindex*)nimotion_Index607A,sizeof(nimotion_Index607A)/sizeof(nimotion_Index607A[0]), 0x607A},
  { (subindex*)nimotion_Index60FF,sizeof(nimotion_Index60FF)/sizeof(nimotion_Index60FF[0]), 0x60FF},
};

const indextable * nimotion_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1014: i = 4;break;
		case 0x1016: i = 5;break;
		case 0x1017: i = 6;break;
		case 0x1018: i = 7;break;
		case 0x1200: i = 8;break;
		case 0x1280: i = 9;break;
		case 0x1400: i = 10;break;
		case 0x1401: i = 11;break;
		case 0x1600: i = 12;break;
		case 0x1601: i = 13;break;
		case 0x1800: i = 14;break;
		case 0x1801: i = 15;break;
		case 0x1802: i = 16;break;
		case 0x1A00: i = 17;break;
		case 0x1A01: i = 18;break;
		case 0x1A02: i = 19;break;
		case 0x2000: i = 20;break;
		case 0x2001: i = 21;break;
		case 0x2002: i = 22;break;
		case 0x6040: i = 23;break;
		case 0x6041: i = 24;break;
		case 0x6060: i = 25;break;
		case 0x6064: i = 26;break;
		case 0x606C: i = 27;break;
		case 0x607A: i = 28;break;
		case 0x60FF: i = 29;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &nimotion_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status nimotion_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index nimotion_firstIndex = {
  8, /* SDO_SVR */
  9, /* SDO_CLT */
  10, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const quick_index nimotion_lastIndex = {
  8, /* SDO_SVR */
  9, /* SDO_CLT */
  11, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const UNS16 nimotion_ObjdictSize = sizeof(nimotion_objdict)/sizeof(nimotion_objdict[0]); 

CO_Data nimotion_Data = CANOPEN_NODE_DATA_INITIALIZER(nimotion);

