
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef NIMOTION_H
#define NIMOTION_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 nimotion_valueRangeTest (UNS8 typeValue, void * value);
const indextable * nimotion_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data nimotion_Data;
extern UNS8 target_torque_6071;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 torque_actual_value_6077;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 max_velocity_6080;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6064, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // NIMOTION_H
